<?php require_once('Connections/mydb.php'); ?>
<?php
mysqli_select_db($mydb, $database_mydb);
$query_Recordset1 = "SELECT * FROM links";
$Recordset1 = mysqli_query( $mydb, $query_Recordset1) or die(mysqli_error());
/*$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);*/
?>
<!DOCTYPE HTML>
<HTML>
  <HEAD>
  <meta name="viewport" content="width=device-width">
  <TITLE>MarinePix               Underwater Photography</TITLE>
  <META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <LINK href="http://www.marinepix.co.uk/res/css/slideshow.css" rel="stylesheet" type="text/css">
  <LINK href="http://www.marinepix.co.uk/res/css/prints.css" rel="stylesheet" type="text/css">
  <LINK href="http://www.marinepix.co.uk/res/css/responsivemenus.css" rel="stylesheet" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-46728061-1', 'marinepix.co.uk');
  ga('send', 'pageview');
  </script>
  </HEAD>
  <BODY>
<?php include ("title.php"); ?>
<?php include ("menus.php"); ?>
<div class="abscentre">
    <div style="display:block;">
    <?php

  $icount=0;
  while($row = mysqli_fetch_assoc($Recordset1))
  {
	  $styling = "";
	  if ($row['imgstyle']!="")
      {
	      $styling = "style=\"".$row['imgstyle']."\"";
      }

	  $desc = htmlspecialchars_decode($row['description']);

	  $class = $row['class'];
	  if (strpos($class, "amazon") !== false) {
		echo '<div class="' . $class . '" align="center">'; //the amazon class should be ignored
		echo '<a href="'.  $row['aref'].  '" target="_new">';
		echo '<img class="amazonimg" border="0" src="' . $row['imageref'] .'" alt="' .$row['alt']. '"><br>'. $desc .'</a><img src="https://ir-uk.amazon-adsystem.com/e/ir?t=mari-21&l=li2&o=2&a=1781452229" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /></div>';
	  }
//	  elseif (strpos($class, "script") !== false ) {
//		  if ($row['script1'] != null || $row['script2'] !=null ){
//			  //script1 is always a local script, script2 is always a src= script
//			  echo '<div class="' . $class. '" align="center">';
//		  }
//		  if ($row['script1'] != null) {
//	          $script1 = $row['script1'];
//			  $rob = html_entity_decode($script1);
//			  
//			  //echo "<!--".$script1."--><br>";
//			  //echo "<!--".$rob."--><br>";
//		  
//$complete1 = "<script type=\"text/javascript\"> ";
//			      $complete1 .= $rob; //the actual script code
//				  $complete1 .= "</scrixxxxpt>";
//			  //echo "<!--".$complete1."--><br>";
//			  /*echo '<script type="text/javascript" '.$rob.'</scrxxxxipt>';*/
//              echo $complete1;
//		  }
//		  if ($row['script2'] != null){
//			  $script2 = $row['script2'];
//			  $script2 = html_entity_decode($script2);
//			  $complete2 =  "<script type=\"text/javascript\" ".$script2."></scrxxxipt>";
////var_dump($complete);
////echo "<!--";
//			  echo $complete2;
////echo "-->";
//		  }
//echo "</div>";
//	  	}
	  else {
		  echo '<a class="'.  $class.  '" href="'.  $row['aref'].  '" target="_blank"> <img src="' . $row['imageref'] .'" ' .$styling. ' alt="' .$row['alt']. '">'. $desc .'</a>';
	  }

    $icount++;
    }
?>	
        <div class="linkblock linkblocklarge" align="center"> 
        <script type="text/javascript"> moWWidgetParams="moAllowUserLocation:true~moBackgroundColour:white~moColourScheme:white~moDays:5~moDomain:www.metoffice.gov.uk~moFSSI:354671~moListStyle:vertical~moMapDisplay:side~moMapsRequired:CloudAndRain,Pressure~moShowFeelsLike:true~moShowUV:true~moShowWind:true~moSpeedUnits:M~moStartupLanguage:en~moTemperatureUnits:C~moTextColour:black~moGridParams:wind,gust,weather,pop,temperature~"; </script>
          <script type="text/javascript" src="http://www.metoffice.gov.uk/public/pws/components/yoursite/loader.js"> </script>
          <p>This <a href='http://www.metoffice.gov.uk/public/weather/forecast/?tab=map' target='_blank' >weather forecast</a> is generated by the <a href='http://www.metoffice.gov.uk/public/weather/components'>Met Office Weather Widget</a></p>
        </div>
	    <div class="linkblock" align="center"> 
          <script type="text/javascript" src="http://www.tidetimes.org.uk/selsey-bill-tide-times.js"></script> 
        </div>
	
	

  </div>
  </div>
</body>
</html>